name: Format Check

# Run on all push and pull requests
on:
  push:
  pull_request:
  workflow_call:

# Force bash to apply pipefail option so pipeline failures aren't masked
defaults:
  run:
    shell: bash

env:
  FOUNDRY_PROFILE: ci

jobs:
  #Checks for duplicate actions. Skips push actions if there is a matching or duplicate pull-request action.
  check-for-duplicates:
    name: Check for duplicates
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          concurrent_skipping: 'same_content'
          skip_after_successful_duplicate: 'true'
          do_not_skip: '["pull_request", "workflow_dispatch", "schedule"]'

  format-checker:
    name: Run format check
    #Continue if check-for-duplicates found no duplicates. Always runs for pull-requests.
    needs: check-for-duplicates
    if: ${{ needs.check-for-duplicates.outputs.should_skip != 'true' }}
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps: 
      - name: Checkout bundle
        uses: actions/checkout@v3
        with:
          submodules: recursive
          repository: shaave/v1-core

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Generate format differences
        run: |
          forge fmt
          git diff > $GITHUB_WORKSPACE/style_differences.txt

      - name: Archive Static Analysis Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: style_differences
          path: style_differences.txt

      - name: Error on differences
        run: |
          if [[ -s style_differences.txt ]];
          then
            cat style_differences.txt
            exit -1
          fi